name: MultiSuSiE
channels:
  - conda-forge
  - esri
  - scitools
  - obspy
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.20,<2
  - scipy>=1.4.1
  - numba>=0.51.2
  - tqdm
  - jupyterlab