name: MultiSuSiE
channels:
  - conda-forge
  - esri
  - scitools
  - obspy
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.20,<2 # numpy<2 isn't necessary, but uses less memory
  - scipy>=1.4.1
  - numba>=0.51.2
  - tqdm
  - jupyterlab # only required for the example, feel free to drop
  - pandas # only required for the example, feel free to drop
